name: maven-build

on:
  pull_request:
    branches:
      - master
# Do not execute only for specific paths if workflow is required.
# https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 11
          - 17
          - 21

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: corretto
          cache: maven

      - name: Build with Maven
        run: >
          mvn
          --batch-mode
          --file pom.xml
          -Pcoverage
          -Dsytle.colors=always
          --errors
          package

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  integration-test:

    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 11
          - 17
          - 21

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: corretto
          cache: maven

      - name: Bring up Skyramp worker
        run: >
          docker run 
          --detach 
          --restart always 
          -p8081:8081 
          -p35142:35142 
          --volume worker:/etc/skyramp 
          public.ecr.aws/j1n2c2p2/rampup/worker:latest

      - name: Install Skyramp
        run: bash -c "$(curl -fsSL https://skyramp.dev/installer.sh)"

      - name: Apply Skyramp mock configurations
        run: >
          skyramp mocker apply 
          --address localhost:35142
          --path skyramp
          mock-gh

      - name: Run integration tests
        run: >
          mvn
          --batch-mode
          --file pom.xml
          -Dsytle.colors=always
          --errors
          -DskipUnitTests
          verify
